// AAA pilot round 7 — L6 regeneration. For every L5 main under the pilot L4,
// the FULL action pool (the main's own actions plus everything in its nested
// supporting/verify tasks) regroups into clean thematic L6 tasks — e.g.
// "Document requirements specification" → Document functional requirements /
// Document non-functional requirements / Document security requirements —
// each single-actor, generated by Sonnet from the actual actions. Every
// action's Definition of Done absorbs its verification detail in the reviewed
// format: "Done when in <App> <pass condition>"; the separate Verify rows are
// then deleted, as are the emptied old nested tasks. The L5 keeps its owner
// and becomes the horizontal grouping level; L6 carries all actions.
// Run: npx tsx --env-file=.env scripts/aaa-l6-regroup.ts
import Anthropic from '@anthropic-ai/sdk';
import { Prisma } from '@prisma/client';
import { prisma } from '../src/db/prisma.js';
import { taskPlans } from '../src/lib/workPlan.js';
import { parseAaaSubTasks, type AaaSubTask } from '../src/lib/subTaskAaa.js';

const L4 = '73fd2dd4-2e01-4ca5-b4b2-3d4d3569d237';
const L6_TYPE = 'cmqssmorj0003j6a7a77y7wu7';
const ai = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY!, maxRetries: 2 });

const mains = await prisma.processNode.findMany({
  where: { parentId: L4, isTask: true },
  orderBy: { sortOrder: 'asc' },
  select: { id: true, displayValue: true, companyId: true, attributes: true, automatability: true },
});
const companyId = mains[0].companyId;
const catalog = await prisma.application.findMany({
  where: { companyId },
  select: { id: true, name: true },
});

const roleCache = new Map<string, string>();
async function roleId(name: string): Promise<string> {
  const hit = roleCache.get(name);
  if (hit) return hit;
  let r = await prisma.role.findFirst({
    where: { companyId, displayValue: name },
    select: { id: true },
  });
  r ??= await prisma.role.create({
    data: { companyId, dbValue: name, displayValue: name },
    select: { id: true },
  });
  roleCache.set(name, r.id);
  return r.id;
}

type PoolItem = {
  key: number; // index in pool
  sourceTaskId: string;
  actor: string;
  action: string;
  steps: string[];
  doneWhen: string | null;
  passWhen: string | null;
  apps: string[];
  actionRowId: string;
  verifyRowId: string | null;
};

const GROUP_SYSTEM = [
  'You organize one operating-model task (insurance carrier IT) into L6 sub-groups.',
  'Input: the task name and its pool of atomic actions (actor, action, apps).',
  'Output: 2-6 thematic L6 tasks that partition the pool — every action index',
  'assigned to EXACTLY one group; each group SINGLE-actor (all its actions share',
  'one actor); names imperative and outcome-shaped like "Document functional',
  'requirements", "Document non-functional requirements", "Document security',
  'requirements" — concise, no app names unless essential. Order groups in',
  'execution order. Reply ONLY minified JSON:',
  '{"groups":[{"name":"...","actor":"...","actions":[<idx>,...]},...]}',
].join(' ');

for (const main of mains) {
  const attrs = (main.attributes ?? {}) as Prisma.JsonObject;
  if (attrs.l6Regrouped === true) {
    console.log(`skip (already regrouped): ${main.displayValue}`);
    continue;
  }
  const children = await prisma.processNode.findMany({
    where: { parentId: main.id, isTask: true },
    select: { id: true, displayValue: true },
  });
  const taskIds = [main.id, ...children.map((c) => c.id)];
  const plans = await taskPlans(taskIds, {});
  const appNames = catalog.map((c) => c.name);

  // Build the pool with row ids so rows can be moved/rewritten in place.
  const pool: PoolItem[] = [];
  for (const tid of taskIds) {
    const p = plans.get(tid);
    if (!p) continue;
    const { subTasks } = parseAaaSubTasks(p.checklist, p.testing, appNames);
    const rows = await prisma.nodeTemplateAnswer.findMany({
      where: { processNodeId: tid, templateKeyId: null, NOT: { customKey: null } },
      select: { id: true, customKey: true, kind: true },
    });
    const byN = new Map<number, { action?: string; verify?: string }>();
    for (const r of rows) {
      const m = r.customKey!.match(/^(\d+)\. (Verify[ :])?/);
      if (!m) continue;
      const e = byN.get(Number(m[1])) ?? {};
      if (m[2] || r.kind === 'TEST') e.verify = r.id;
      else e.action = r.id;
      byN.set(Number(m[1]), e);
    }
    for (const s of subTasks) {
      const ids = byN.get(s.n);
      if (!ids?.action) continue;
      pool.push({
        key: pool.length,
        sourceTaskId: tid,
        actor: s.actor ?? 'Unknown',
        action: s.action,
        steps: s.steps,
        doneWhen: s.doneWhen,
        passWhen: s.verify?.passWhen ?? null,
        apps: s.apps,
        actionRowId: ids.action,
        verifyRowId: ids.verify ?? null,
      });
    }
  }
  if (pool.length < 2) {
    console.log(`skip (${pool.length} actions): ${main.displayValue}`);
    continue;
  }

  // Sonnet proposes the L6 partition.
  const prompt = `Task: "${main.displayValue}"\nActions:\n${pool
    .map(
      (p) => `${p.key}: [${p.actor}] ${p.action}${p.apps.length ? ` (${p.apps.join(', ')})` : ''}`,
    )
    .join('\n')}`;
  let groups: { name: string; actor: string; actions: number[] }[];
  try {
    const r = await ai.messages.create({
      model: 'claude-sonnet-5',
      max_tokens: 2500,
      system: GROUP_SYSTEM,
      messages: [{ role: 'user', content: prompt }],
    });
    const text = r.content
      .filter((b): b is Anthropic.TextBlock => b.type === 'text')
      .map((b) => b.text)
      .join(' ')
      .trim()
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/, '');
    groups = (JSON.parse(text) as { groups: typeof groups }).groups ?? [];
  } catch (e) {
    console.log(`AI grouping failed for "${main.displayValue}": ${(e as Error).message}`);
    continue;
  }
  // Validate the partition: every index exactly once, group actors consistent.
  const seen = new Set<number>();
  let valid = groups.length >= 1;
  for (const g of groups) {
    for (const i of g.actions) {
      if (!pool[i] || seen.has(i)) valid = false;
      seen.add(i);
    }
  }
  if (!valid || seen.size !== pool.length) {
    console.log(
      `invalid partition for "${main.displayValue}" (${seen.size}/${pool.length}) — one group per actor fallback`,
    );
    const byActor = new Map<string, number[]>();
    for (const p of pool) byActor.set(p.actor, [...(byActor.get(p.actor) ?? []), p.key]);
    groups = [...byActor.entries()].map(([actor, actions]) => ({
      name: `${main.displayValue} — ${actor}`,
      actor,
      actions,
    }));
  }

  // Apply: new L6 nodes; rows move in with merged DoD; verify rows delete.
  const ancestors = await prisma.processNodeClosure.findMany({
    where: { descendantId: main.id },
    select: { ancestorId: true, depth: true },
  });
  const delivLinks = await prisma.nodeDeliverable.findMany({
    where: { processNodeId: main.id },
    select: { deliverableId: true },
  });
  let gi = 0;
  for (const g of groups) {
    gi += 1;
    const rid = await roleId(g.actor);
    const node = await prisma.$transaction(async (tx) => {
      const n = await tx.processNode.create({
        data: {
          companyId,
          parentId: main.id,
          processLevelTypeId: L6_TYPE,
          dbValue: g.name,
          displayValue: g.name,
          isTask: true,
          sortOrder: gi,
          automatability: main.automatability,
        },
        select: { id: true },
      });
      await tx.processNodeClosure.createMany({
        data: [
          { ancestorId: n.id, descendantId: n.id, depth: 0 },
          ...ancestors.map((a) => ({
            ancestorId: a.ancestorId,
            descendantId: n.id,
            depth: a.depth + 1,
          })),
        ],
      });
      await tx.nodeRole.create({
        data: { companyId, processNodeId: n.id, roleId: rid, role_: 'Owner' },
      });
      await tx.nodeDeliverable.createMany({
        data: delivLinks.map((d) => ({
          companyId,
          processNodeId: n.id,
          deliverableId: d.deliverableId,
        })),
      });
      return n;
    });
    let k = 0;
    for (const idx of g.actions) {
      const p = pool[idx];
      k += 1;
      // The action's DoD absorbs the verification detail: prefer the tested
      // pass-condition, prefixed by the application it is checked in.
      const cond = p.passWhen ?? p.doneWhen ?? 'the action is complete';
      const app = p.apps[0];
      const dod = `Done when${app ? ` in ${app}` : ''} ${cond}`;
      const value = [`By the ${g.actor}:`, ...p.steps.map((s, i) => `${i + 1}) ${s}`), dod].join(
        '\n',
      );
      await prisma.nodeTemplateAnswer.update({
        where: { id: p.actionRowId },
        data: {
          processNodeId: node.id,
          customKey: `${k}. ${p.action}`,
          value,
          kind: 'CHECKLIST',
          sortOrder: 100 + k * 10,
        },
      });
      if (p.verifyRowId) await prisma.nodeTemplateAnswer.delete({ where: { id: p.verifyRowId } });
    }
    // Apps referenced by the group's actions.
    const groupApps = [...new Set(g.actions.flatMap((i) => pool[i].apps))];
    const appRows = catalog.filter((c) => groupApps.includes(c.name));
    if (appRows.length)
      await prisma.nodeAppUsage.createMany({
        data: appRows.map((a) => ({
          companyId,
          processNodeId: node.id,
          applicationId: a.id,
          usageType: 'performed',
        })),
      });
    console.log(`  L6 "${g.name}" (${g.actor}, ${g.actions.length} actions)`);
  }

  // Old children emptied of rows → delete; the main keeps no direct rows.
  for (const c of children) {
    const left = await prisma.nodeTemplateAnswer.count({ where: { processNodeId: c.id } });
    if (left === 0) await prisma.processNode.delete({ where: { id: c.id } });
    else console.log(`  old child kept (${left} rows): ${c.displayValue}`);
  }
  await prisma.processNode.update({
    where: { id: main.id },
    data: { attributes: { ...attrs, l6Regrouped: true } },
  });
  console.log(
    `regrouped: ${main.displayValue} → ${groups.length} L6 tasks (${pool.length} actions)`,
  );
}

const top = await prisma.processNode.count({ where: { parentId: L4, isTask: true } });
const l6 = await prisma.processNode.count({ where: { parent: { parentId: L4 }, isTask: true } });
console.log(`\nDone: ${top} L5 mains, ${l6} L6 tasks`);
await prisma.$disconnect();
