// Ontology / taxonomy exporter (Product Model Workspace plan §2/1-C, §6.3).
//
// Exports the company's operating-model vocabularies as SKOS in three formats,
// written to documents/taxonomy/ with dated filenames (committed snapshots):
//   1. Turtle           taxonomy-<company>-<date>.ttl
//   2. Flat JSON        taxonomy-<company>-<date>.json        ({ nodes: [...] })
//   3. Viewer JSON      taxonomy-viewer-<company>-<date>.json ({l, n, e, c} trees)
//
// Six concept schemes: process (ProcessNode tree), organization (OrgUnit tree),
// standards (Standard tree), applications (Application by kind), roles (Role by
// OrgUnit), product-model (11 components -> ProductModelAnatomyCategory rows).
// URI contract (§6.3): tb: = https://w3id.org/transformation-bridge/ontology#,
// tbi: = https://w3id.org/transformation-bridge/id/; schemes tbi:scheme-<key>;
// product-model concepts tbi:pm-<component-slug> (top) and tbi:pma-<slug>
// (children) with skos:notation = sortOrder, skos:scopeNote = scope and
// skos:related linking SEGMENT/GEOGRAPHY concepts to their COMMON core
// (the component top concept).
//
// Run from backend/:  npx tsx --env-file=.env scripts/export-taxonomy.ts
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { prisma } from '../src/db/prisma.js';
import { PRODUCT_COMPONENTS, type ProductComponent } from '../src/seed/seedWorkspaceVocabulary.js';
import { COMPONENT_SLUGS, slugify } from '../src/seed/seedProductModelAnatomy.js';

export type Concept = {
  id: string; // tbi: local part
  label: string;
  notation: string | null;
  parentId: string | null; // tbi: local part of the broader concept
  related?: string[]; // tbi: local parts (skos:related)
  scopeNote?: string | null; // skos:scopeNote (product-model: the scope)
  extra?: Record<string, string>;
};

export type Scheme = { key: string; label: string; concepts: Concept[] };

export type ViewerNode = {
  l: string; // label
  n: string | null; // notation
  e: Record<string, string> | null; // extra
  c: ViewerNode[]; // children
};

// ── TTL serialization ──────────────────────────────────────────────────

export const ttlEscape = (s: string): string =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, '\\n');

export function serializeTtl(schemes: Scheme[], companyName: string, date: string): string {
  const out: string[] = [
    '@prefix skos: <http://www.w3.org/2004/02/skos/core#> .',
    '@prefix tb: <https://w3id.org/transformation-bridge/ontology#> .',
    '@prefix tbi: <https://w3id.org/transformation-bridge/id/> .',
    '@prefix dct: <http://purl.org/dc/terms/> .',
    '',
    `# Transformation Bridge taxonomy export — ${ttlEscape(companyName)} — ${date}`,
    `# Generated by backend/scripts/export-taxonomy.ts`,
    '',
  ];
  for (const scheme of schemes) {
    out.push(
      `tbi:scheme-${scheme.key} a skos:ConceptScheme ;`,
      `  skos:prefLabel "${ttlEscape(scheme.label)}"@en ;`,
      `  dct:created "${date}" .`,
      '',
    );
    for (const c of scheme.concepts) {
      const lines = [
        `tbi:${c.id} a skos:Concept`,
        `  skos:prefLabel "${ttlEscape(c.label)}"@en`,
        `  skos:inScheme tbi:scheme-${scheme.key}`,
      ];
      if (c.notation !== null) lines.push(`  skos:notation "${ttlEscape(c.notation)}"`);
      if (c.parentId) lines.push(`  skos:broader tbi:${c.parentId}`);
      else lines.push(`  skos:topConceptOf tbi:scheme-${scheme.key}`);
      if (c.scopeNote) lines.push(`  skos:scopeNote "${ttlEscape(c.scopeNote)}"@en`);
      for (const rel of c.related ?? []) lines.push(`  skos:related tbi:${rel}`);
      out.push(lines.join(' ;\n') + ' .', '');
    }
  }
  return out.join('\n');
}

// ── Viewer tree ({l, n, e, c}) ─────────────────────────────────────────

export function buildViewerTrees(concepts: Concept[]): ViewerNode[] {
  const nodeById = new Map<string, ViewerNode>();
  for (const c of concepts) {
    nodeById.set(c.id, {
      l: c.label,
      n: c.notation,
      e: c.scopeNote ? { scope: c.scopeNote, ...(c.extra ?? {}) } : (c.extra ?? null),
      c: [],
    });
  }
  const roots: ViewerNode[] = [];
  for (const c of concepts) {
    const node = nodeById.get(c.id);
    if (node === undefined) continue;
    const parent = c.parentId ? nodeById.get(c.parentId) : undefined;
    if (parent) parent.c.push(node);
    else roots.push(node);
  }
  return roots;
}

export function countViewerNodes(nodes: ViewerNode[]): number {
  let n = 0;
  const stack = [...nodes];
  while (stack.length) {
    const node = stack.pop();
    if (!node) break;
    n++;
    stack.push(...node.c);
  }
  return n;
}

// ── Scheme builders ────────────────────────────────────────────────────

async function buildSchemes(companyId: string): Promise<Scheme[]> {
  // 1. process — the ProcessNode spine.
  const nodes = await prisma.processNode.findMany({
    where: { companyId },
    select: { id: true, displayValue: true, parentId: true, code: true, isTask: true },
    orderBy: { sortOrder: 'asc' },
  });
  const process: Scheme = {
    key: 'process',
    label: 'Process (value-stream spine)',
    concepts: nodes.map((n) => ({
      id: `pn-${n.id}`,
      label: n.displayValue,
      notation: n.code ?? null,
      parentId: n.parentId ? `pn-${n.parentId}` : null,
      extra: n.isTask ? { task: 'true' } : undefined,
    })),
  };

  // 2. organization — the OrgUnit spine.
  const orgUnits = await prisma.orgUnit.findMany({
    where: { companyId },
    select: { id: true, displayValue: true, parentId: true },
    orderBy: { sortOrder: 'asc' },
  });
  const organization: Scheme = {
    key: 'organization',
    label: 'Organization (org spine)',
    concepts: orgUnits.map((o) => ({
      id: `ou-${o.id}`,
      label: o.displayValue,
      notation: null,
      parentId: o.parentId ? `ou-${o.parentId}` : null,
    })),
  };

  // 3. standards — the Standard tree (groups + leaves).
  const stds = await prisma.standard.findMany({
    where: { companyId },
    select: { id: true, name: true, parentId: true, category: true },
    orderBy: { name: 'asc' },
  });
  const standards: Scheme = {
    key: 'standards',
    label: 'Standards',
    concepts: stds.map((s) => ({
      id: `std-${s.id}`,
      label: s.name,
      notation: null,
      parentId: s.parentId ? `std-${s.parentId}` : null,
      extra: s.category ? { category: s.category } : undefined,
    })),
  };

  // 4. applications — Application grouped by kind.
  const apps = await prisma.application.findMany({
    where: { companyId },
    select: { id: true, name: true, kind: true, category: true },
    orderBy: { name: 'asc' },
  });
  const kinds = [...new Set(apps.map((a) => a.kind))].sort();
  const applications: Scheme = {
    key: 'applications',
    label: 'Applications (estate)',
    concepts: [
      ...kinds.map((k) => ({
        id: `app-kind-${slugify(k)}`,
        label: k,
        notation: null,
        parentId: null,
      })),
      ...apps.map((a) => ({
        id: `app-${a.id}`,
        label: a.name,
        notation: null,
        parentId: `app-kind-${slugify(a.kind)}`,
        extra: a.category ? { category: a.category } : undefined,
      })),
    ],
  };

  // 5. roles — Role grouped by its home OrgUnit.
  const roles = await prisma.role.findMany({
    where: { companyId },
    select: { id: true, displayValue: true, orgUnitId: true, roleFamily: true },
    orderBy: { displayValue: 'asc' },
  });
  const orgById = new Map(orgUnits.map((o) => [o.id, o.displayValue]));
  const usedOrgIds = [...new Set(roles.map((r) => r.orgUnitId).filter((v) => v !== null))];
  const rolesScheme: Scheme = {
    key: 'roles',
    label: 'Roles',
    concepts: [
      ...usedOrgIds.map((id) => ({
        id: `role-grp-${id}`,
        label: orgById.get(id) ?? 'Org unit',
        notation: null,
        parentId: null,
      })),
      { id: 'role-grp-unassigned', label: 'Unassigned', notation: null, parentId: null },
      ...roles.map((r) => ({
        id: `role-${r.id}`,
        label: r.displayValue,
        notation: null,
        parentId: r.orgUnitId ? `role-grp-${r.orgUnitId}` : 'role-grp-unassigned',
        extra: r.roleFamily ? { family: r.roleFamily } : undefined,
      })),
    ],
  };

  // 6. product-model — the 11 components + the anatomy catalog (§6.3):
  // top concepts tbi:pm-<component-slug>; children tbi:pma-<slug>;
  // skos:notation = sortOrder; skos:scopeNote = scope; skos:related links
  // SEGMENT/GEOGRAPHY concepts to their COMMON core (the component concept).
  const anatomy = await prisma.productModelAnatomyCategory.findMany({
    where: { companyId },
    select: {
      slug: true,
      name: true,
      component: true,
      scope: true,
      view: true,
      sortOrder: true,
      recommendedComponent: true,
    },
    orderBy: [{ component: 'asc' }, { scope: 'asc' }, { sortOrder: 'asc' }],
  });
  const productModel: Scheme = {
    key: 'product-model',
    label: 'Product model anatomy',
    concepts: [
      ...PRODUCT_COMPONENTS.map((cmp, i) => ({
        id: `pm-${COMPONENT_SLUGS[cmp]}`,
        label: cmp,
        notation: String(i),
        parentId: null,
      })),
      ...anatomy.map((a) => ({
        id: `pma-${a.slug}`,
        label: a.name,
        notation: String(a.sortOrder),
        parentId: `pm-${COMPONENT_SLUGS[a.component as ProductComponent] ?? slugify(a.component)}`,
        scopeNote: a.scope,
        related:
          a.scope === 'SEGMENT' || a.scope === 'GEOGRAPHY'
            ? [`pm-${COMPONENT_SLUGS[a.component as ProductComponent] ?? slugify(a.component)}`]
            : undefined,
        extra: {
          view: a.view,
          ...(a.recommendedComponent ? { recommendedComponent: a.recommendedComponent } : {}),
        },
      })),
    ],
  };

  return [process, organization, standards, applications, rolesScheme, productModel];
}

// ── Main ───────────────────────────────────────────────────────────────

async function main() {
  const company = await prisma.company.findFirst({
    select: { id: true, name: true, slug: true },
  });
  if (!company) throw new Error('No company found on the active database');

  const now = new Date();
  const date = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(
    now.getDate(),
  ).padStart(2, '0')}`;
  const schemes = await buildSchemes(company.id);

  const here = dirname(fileURLToPath(import.meta.url));
  const outDir = resolve(here, '../../documents/taxonomy');
  mkdirSync(outDir, { recursive: true });

  // 1. Turtle
  const ttlPath = resolve(outDir, `taxonomy-${company.slug}-${date}.ttl`);
  writeFileSync(ttlPath, serializeTtl(schemes, company.name, date), 'utf8');

  // 2. Flat JSON
  const flat = {
    generated: date,
    company: company.slug,
    namespaces: {
      tb: 'https://w3id.org/transformation-bridge/ontology#',
      tbi: 'https://w3id.org/transformation-bridge/id/',
    },
    schemes: schemes.map((s) => ({
      id: `scheme-${s.key}`,
      label: s.label,
      count: s.concepts.length,
    })),
    nodes: schemes.flatMap((s) =>
      s.concepts.map((c) => ({
        id: c.id,
        label: c.label,
        notation: c.notation,
        parentId: c.parentId,
        scheme: s.key,
        extra: {
          ...(c.scopeNote ? { scope: c.scopeNote } : {}),
          ...(c.extra ?? {}),
        },
      })),
    ),
  };
  const flatPath = resolve(outDir, `taxonomy-${company.slug}-${date}.json`);
  writeFileSync(flatPath, JSON.stringify(flat, null, 1), 'utf8');

  // 3. Viewer JSON ({l, n, e, c} trees per scheme)
  const viewer = {
    generated: date,
    company: company.slug,
    schemes: schemes.map((s) => ({
      id: `scheme-${s.key}`,
      label: s.label,
      count: s.concepts.length,
      trees: buildViewerTrees(s.concepts),
    })),
  };
  const viewerPath = resolve(outDir, `taxonomy-viewer-${company.slug}-${date}.json`);
  writeFileSync(viewerPath, JSON.stringify(viewer), 'utf8');

  console.log(`Exported to ${outDir}`);
  for (const s of schemes) {
    const treeCount = countViewerNodes(buildViewerTrees(s.concepts));
    const ok = treeCount === s.concepts.length ? 'OK' : 'XX';
    console.log(
      `${ok}  ${s.key.padEnd(14)} ${String(s.concepts.length).padStart(6)} concepts (viewer tree ${treeCount})`,
    );
  }
  console.log(`   ${ttlPath}`);
  console.log(`   ${flatPath}`);
  console.log(`   ${viewerPath}`);
}

const isMain =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      return prisma.$disconnect().then(() => process.exit(1));
    });
}
